- name: Create dockerfile from template
  ansible.builtin.template:
    src: docker_temp.j2
    dest: "~/Dockerfile"

- name: Create directory
  file:
    path: /var/www/html
    state: directory

- name: Copy Index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

#"{{ role_path }}/files"
- name: Build image from Dockerfile
  docker_image:
    build:
      path: .
      pull: no
    state: present
    source: build
    name: "{{image_name}}"

- name: Push image to local repo
  docker_image:
    name: "{{ image_name }}"
    tag: latest
    repository: "localhost:{{ registry_port }}/{{image_name}}"
    push: yes
    force_tag: yes #to force image pushing into repository
    source: local

- name: Remove old image
  docker_image:
    name: "{{image_name}}"
    state: absent

- name: Remove centos:8 image
  docker_image:
    name: centos
    tag: '8'
    state: absent